---
title: "STA 4320 Homework 7"
author: "Eric Muro"
date: "11/7/18"
output: html_document
---

# Question 4 ISLR 6.8.8


## Solution.

### Part (a)

```{r}
set.seed(1)
x = rnorm(100)
eps = rnorm(100)
```

### Part (b)

```{r}
b0 = 10
b1 = 1
b2 = -5
b3 = 2
y = b0 + b1*x + b2*x^2 + b3*x^3 + eps
```


### Part (c)

```{r}
library(leaps)
data.full <- data.frame(y=y,x=x)
regfit.full <- regsubsets(y~x+I(x^2)+I(x^3)+I(x^4)+I(x^5)+I(x^6)+I(x^7)+I(x^8)+I(x^9)+I(x^10), data=data.full,nvmax=10)
reg.summary <- summary(regfit.full)
par(mfrow=c(2,2))
plot(reg.summary$cp,xlab = "Number of variables",ylab = "C_p",type = "l")
points(which.min(reg.summary$cp),reg.summary$cp[which.min(reg.summary$cp)],col = "red",cex=2,pch=20)
plot(reg.summary$bic,xlab = "Number of variables",ylab = "BIC",type = "l")
points(which.min(reg.summary$bic),reg.summary$bic[which.min(reg.summary$bic)],col = "red",cex=2,pch=20)
plot(reg.summary$adjr2,xlab = "Number of variables",ylab = "Adjusted R^2",type = "l")
points(which.max(reg.summary$adjr2),reg.summary$adjr2[which.max(reg.summary$adjr2)],col = "red", cex=2,pch=20)
```

```{r}
coef(regfit.full, which.max(reg.summary$adjr2))
```


### Part (d)

```{r}
regfit.bwd <- regsubsets(y~x+I(x^2)+I(x^3)+I(x^4)+I(x^5)+I(x^6)+I(x^7)+I(x^8)+I(x^9)+I(x^10),data=data.full,nvmax=10,method="backward")
reg.summary.bwd <- summary(regfit.bwd)
par(mfrow=c(2,2))
plot(reg.summary.bwd$cp,xlab="Number of variables", ylab="C_p",type="l")
points(which.min(reg.summary.bwd$cp),reg.summary.bwd$cp[which.min(reg.summary.bwd$cp)],col="red",cex=2,pch=20)
plot(reg.summary.bwd$bic,xlab="Number of variables", ylab="BIC",type="l")
points(which.min(reg.summary.bwd$bic),reg.summary.bwd$bic[which.min(reg.summary.bwd$bic)],col="red",cex=2,pch=20)
plot(reg.summary.bwd$adjr2,xlab="Number of variables", ylab="Adjusted R^2",type="l")
points(which.min(reg.summary.bwd$adjr2),reg.summary.bwd$adjr2[which.min(reg.summary.bwd$adjr2)],col="red",cex=2,pch=20)
mtext("Plots of Mallow's C_p, BIC, and Adjusted R^2 for backwards stepwise selection",side = 3, line = -2, outer=TRUE)
coef(regfit.bwd,which.max(reg.summary.bwd$adjr2))
```

```{r}
regfit.fwd <- regsubsets(y~x+I(x^2)+I(x^3)+I(x^4)+I(x^5)+I(x^6)+I(x^7)+I(x^8)+I(x^9)+I(x^10),data=data.full,nvmax=10,method="forward")
reg.summary.fwd <- summary(regfit.fwd)
par(mfrow=c(2,2))
plot(reg.summary.fwd$cp,xlab="Number of variables", ylab="C_p",type="l")
points(which.min(reg.summary.fwd$cp),reg.summary.fwd$cp[which.min(reg.summary.fwd$cp)],col="red",cex=2,pch=20)
plot(reg.summary.fwd$bic,xlab="Number of variables", ylab="BIC",type="l")
points(which.min(reg.summary.fwd$bic),reg.summary.fwd$bic[which.min(reg.summary.fwd$bic)],col="red",cex=2,pch=20)
plot(reg.summary.fwd$adjr2,xlab="Number of variables", ylab="Adjusted R^2",type="l")
points(which.min(reg.summary.fwd$adjr2),reg.summary.fwd$adjr2[which.min(reg.summary.fwd$adjr2)],col="red",cex=2,pch=20)
mtext("Plots of Mallow's C_p, BIC, and Adjusted R^2 for forward stepwise selection", side = 3, line = -2, outer = TRUE)
coef(regfit.fwd,which.max(reg.summary.fwd$adjr2))
```


### Part (e)

```{r}
library(glmnet)
xmat <- model.matrix(y~x+I(x^2)+I(x^3)+I(x^4)+I(x^5)+I(x^6)+I(x^7)+I(x^8)+I(x^9)+I(x^10),data=data.full)[,-1]
cv.lasso <- cv.glmnet(xmat,y,alpha=1)
plot(cv.lasso)
```

```{r}
bestlam <- cv.lasso$lambda.min
bestlam
```

```{r}
fit.lasso <- glmnet(xmat,y,alpha=1)
predict(fit.lasso,s=bestlam,type="coefficients")[1:11,]
```


### Part (f)

```{r}
b0 = 10
b7 = 2
y = b0 + b7*x^7 + eps
data.full <- data.frame(y=y, x=x)
regfit.full <- regsubsets(y~x+I(x^2)+I(x^3)+I(x^4)+I(x^5)+I(x^6)+I(x^7)+I(x^8)+I(x^9)+I(x^10), data=data.full,nvmax=10)
reg.summary <- summary(regfit.full)
par(mfrow=c(2,2))
plot(reg.summary$cp,xlab = "Number of variables",ylab = "C_p",type = "l")
points(which.min(reg.summary$cp),reg.summary$cp[which.min(reg.summary$cp)],col = "red",cex=2,pch=20)
plot(reg.summary$bic,xlab = "Number of variables",ylab = "BIC",type = "l")
points(which.min(reg.summary$bic),reg.summary$bic[which.min(reg.summary$bic)],col = "red",cex=2,pch=20)
plot(reg.summary$adjr2,xlab = "Number of variables",ylab = "Adjusted R^2",type = "l")
points(which.max(reg.summary$adjr2),reg.summary$adjr2[which.max(reg.summary$adjr2)],col = "red", cex=2,pch=20)

```

```{r}
coef(regfit.full,1)
coef(regfit.full,2)
coef(regfit.full,4)
```

```{r}
xmat <- model.matrix(y~x+I(x^2)+I(x^3)+I(x^4)+I(x^5)+I(x^6)+I(x^7)+I(x^8)+I(x^9)+I(x^10),data=data.full)[,-1]
cv.lasso <- cv.glmnet(xmat,y,alpha=1)
fit.lasso <- glmnet(xmat,y,alpha=1)
predict(fit.lasso,s=bestlam,type="coefficients")[1:11,]
```


# Question 5 ISLR 6.8.9


## Solution.

### Part (a)

```{r}
library(ISLR)
data(College)
set.seed(11)
train <- sample(1:dim(College)[1],dim(College)[1]/2)
test <- train
college.train <- College[train,]
college.test <- College[test,]
```

### Part (b)

```{r}
fit.lm <- lm(Apps~.,data=college.train)
pred.lm <- predict(fit.lm,college.test)
mean((pred.lm-college.test$Apps)^2)
AIC(fit.lm,k=2)
```


### Part (c)

```{r}
train.mat <- model.matrix(Apps~.,data=college.train)
test.mat <- model.matrix(Apps~.,data=college.test)
grid <- 10^seq(4,-2,length=100)
fit.ridge <- glmnet(train.mat,college.train$Apps,alpha=0,lambda=grid,thresh=1e-12)
cv.ridge <- cv.glmnet(train.mat,college.train$Apps,alpha=0,lambda=grid,thresh=1e-12)
bestlam.ridge=cv.ridge$lambda.min
bestlam.ridge
#AIC(fit.ridge,k=2)
```


### Part (d)

```{r}
fit.lasso <- glmnet(train.mat,college.train$Apps,alpha=1,lambda=grid,thresh=1e-12)

cv.lasso <- cv.glmnet(train.mat,college.train$Apps,alpha=1,lambda=grid,thresh=1e-12)
bestlam.lasso <- cv.lasso$lambda.min
bestlam.lasso
pred.lasso <- predict(fit.lasso,s=bestlam.lasso,newx=test.mat)
mean((pred.lasso-college.test$Apps)^2)
pred.lasso<-predict(fit.lasso,s=bestlam.lasso,type="coefficients")
```


### Part (g)

```{r}
test.avg <- mean(college.test$Apps)
lm.r2 <- 1-mean((pred.lm-college.test$Apps)^2)/mean((test.avg-college.test$Apps)^2)
#ridge.r2 <- 1-mean((pred.ridge-college.test$Apps)^2)/mean((test.avg-college.test$Apps)^2)
lasso.r2 <- 1-mean((pred.lasso-college.test$Apps)^2)/mean((test.avg-college.test$Apps)^2)
```

